ALTER TABLE skills ALTER COLUMN id TYPE BIGINT;

ALTER TABLE profile ALTER COLUMN id TYPE BIGINT;

ALTER TABLE experience ALTER COLUMN id TYPE BIGINT;

ALTER TABLE projects ALTER COLUMN id TYPE BIGINT;

ALTER TABLE contact_messages ALTER COLUMN id TYPE BIGINT;

ALTER TABLE project_skill ALTER COLUMN project_id TYPE BIGINT;

ALTER TABLE project_skill ALTER COLUMN skill_id TYPE BIGINT;

ALTER TABLE admin_users ALTER COLUMN id TYPE BIGINT;
