spring.application.name=portfolio
spring.datasource.url=jdbc:postgresql://localhost:5432/portfolio_dev
spring.datasource.username=postgres
spring.datasource.password=pratham57

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true